Title =  "Mryqu's Notes"
LanguageCode = "zh-CN"
BaseUrl = "https://mryqu.github.io/"
Theme =  "next"
MetaDataFormat =  "yaml"
CanonifyUrls =  true
BuildDrafts =  false
PaginatePath =  "p"
Paginate = 8
DisablePathToLower =  false
HasCJKLanguage = true
PreserveTaxonomyNames = false
UglyUrls = false
PygmentsStyle = "monokai"
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
DefaultContentLanguage = "zh"
defaultContentLanguageInSubdir = false

[Params]
  Introduce = "Programmer & Architect"
  Description = "mryqu | yandongqu | 博客 | 软件 | 架构 | 技术"
  Keywords =  "mryqu,yandongqu,博客,程序员,架构师,笔记,技术,分享"
  Subtitle = ""
  Imglogo = "/img/logo.png"
  AuthorImg = "/img/author.jpg"
  DateFormat = "2006-01-02"
  YearFormat = "2006年"
  MonthFormat = "01-02"  
  #BaiduStatsId = ""
  #QQStatsId = ""
  toc = true
  Fancybox = true

[Author]
  Name = "mryqu"

[Params.Share]
  #DuoShuo = ""
  #Baidu = true

[[menu.main]]
  Name = "首页"
  Pre = "home"
  URL = "/"
  Weight = 1
[[menu.main]]
  Name = "标签"
  Pre = "tags"
  URL = "/tags/"
  Weight = 2
[[menu.main]]
  Name = "分类"
  Pre = "categories"
  URL = "/categories/"
  Weight = 3
[[menu.main]]
  Name = "归档"
  Pre = "archive"
  URL = "/post/"
  Weight = 4

[[languages.en.menu.main]]
  Name = "Home"
  Pre = "home"
  URL = "/"
  Weight = 1
[[languages.en.menu.main]]
  Name = "Tag"
  Pre = "tags"
  URL = "/tags/"
  Weight = 2
[[languages.en.menu.main]]
  Name = "Category"
  Pre = "categories"
  URL = "/categories/"
  Weight = 3
[[languages.en.menu.main]]
  Name = "Archive"
  Pre = "archive"
  URL = "/post/"
  Weight = 4

[[Params.Socials]]
  Name = "GitHub"
  Icon = "github"
  URL = "https://github.com/mryqu"

[[Params.Socials]]
  Name = "Twitter"
  Icon = "twitter"
  URL = "https://twitter.com/yandongqu"  

[[Params.Socials]]
  Name = "FB Page"
  Icon = "facebook"
  URL = "https://www.facebook.com/yandongqu"  

[languages.en]
  languageCode = "en-US"

[languages.zh]
  languageCode = "zh-CN"